import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./Loading";


export const metadata: Metadata = {
  title: "ブログアプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body >
        <Suspense fallback={<Loading/>}>
        {children}
        </Suspense>
      </body>
    </html>
  );
}
